In [1]:
from sqlalchemy import (
    Boolean,
    Column,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    text,
    update,
)

from egomimic.utils.aws.aws_sql import (
    TableRow,
    create_default_engine,
    episode_table_to_df,
)

In [2]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [3]:
df = episode_table_to_df(engine)
df

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
0,696bc6351cafc9f413b5b7e8,695d098f83a9fdf2d84d9a47,mecka,1960.0,packaging_cloths,"In the final part of the video, the person con...",stockroom,"[""plaid_cloths"", ""plastic_bags"", ""cardboard_bo...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bc635...,,s3://rldb/processed_v3/mecka/freeform/696bc635...,None,None
1,696b2152d1aa1f60b4db5ef1,694a6ead5c0479a0fb867619,mecka,2700.0,cleaning_engine_parts,"A mechanic continues to clean a used, three-cy...",service_bay,"[""engine_gasket"", ""workbench"", ""cloth""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b2152...,,s3://rldb/processed_v3/mecka/freeform/696b2152...,None,None
2,696bcb732a9a68766920de81,696452cf83a9fdf2d86552c5,mecka,2252.0,folding_paper_bags,"A person begins folding a new paper bag, caref...",packaging_area,"[""paper_sheet"", ""glue"", ""plastic_container"", ""...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,None,None
3,69b4944484179943aec080c6,6948bbeb5c0479a0fb82ec42,mecka,2278.0,planting_cuttings,Planting plant cuttings into a tray filled wit...,nursery,"[""soil"", ""plant_cuttings"", ""tray"", ""pots""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/69b49444...,,s3://rldb/processed_v3/mecka/freeform/69b49444...,CC BY-SA 4.0,"[{'label': 'adjust soil in container', 'end_se..."
4,693cd014bec8abdc94f9a365,693369d4c195d3a38a24af5c,mecka,2650.0,labeling_eggs,The person uses a pair of scissors to cut labe...,packing_shed,"[""labels"", ""egg_cartons"", ""eggs""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/693cd014...,,s3://rldb/processed_v3/mecka/freeform/693cd014...,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72259,696db125ddefc568d7372680,695b04fc83a9fdf2d8485831,mecka,2698.0,packaging_items,"A person is sitting and packaging small, black...",material_storage,"[""air_stones"", ""plastic_bags"", ""cardboard_box""...",s3://rldb/mecka/freeform/696db125ddefc568d7372680,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696db125...,,s3://rldb/processed_v3/mecka/freeform/696db125...,CC BY-SA 4.0,"[{'label': 'pick up plastic bag, pick up grey ..."
72260,696b9a50a04610abd4bb2ed0,694901865c0479a0fb833c40,mecka,2848.0,decorating_party_horns,A person attaches a pre-made blue fringed pape...,craft_section,"[""party_horn"", ""blue_fringed_paper"", ""white_fr...",s3://rldb/mecka/freeform/696b9a50a04610abd4bb2ed0,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,CC BY-SA 4.0,"[{'label': 'wrap fringe, adjust cone', 'end_se..."
72261,696bac1d7e6f94bf3414388d,6951c933c0d9448524bb1d46,mecka,3598.0,making_kites,A person continues to assemble a kite frame. T...,craft_section,"[""kite_frame"", ""bamboo_sticks"", ""string""]",s3://rldb/mecka/freeform/696bac1d7e6f94bf3414388d,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,CC BY-SA 4.0,[{'label': 'tie two wooden sticks to form a cr...
72262,696babf5b17075c2c32fa74b,694c877362d08e8cd95f46fd,mecka,3598.0,cleaning_shoes,A person is using a brush and soapy water to s...,repair_bench,"[""shoe"", ""soapy_water""]",s3://rldb/mecka/freeform/696babf5b17075c2c32fa74b,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696babf5...,,s3://rldb/processed_v3/mecka/freeform/696babf5...,CC BY-SA 4.0,"[{'label': 'hold shoe, scrub shoe with brush',..."
72263,696bbd5575020a567fd376e9,6959d51cb8d0e4dc08fb48e1,mecka,3202.0,wick_preparation,"The person continues preparing candle wicks, c...",production_area,"[""tealight_cup"", ""wooden_sticks"", ""wick"", ""met...",s3://rldb/mecka/freeform/696bbd5575020a567fd376e9,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,CC BY-SA 4.0,"[{'label': 'pick up sticks, align sticks', 'en..."

In [4]:
# Filter to certain lab
df[df["lab"] == "mecka"]

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
0,696bc6351cafc9f413b5b7e8,695d098f83a9fdf2d84d9a47,mecka,1960.0,packaging_cloths,"In the final part of the video, the person con...",stockroom,"[""plaid_cloths"", ""plastic_bags"", ""cardboard_bo...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bc635...,,s3://rldb/processed_v3/mecka/freeform/696bc635...,None,None
1,696b2152d1aa1f60b4db5ef1,694a6ead5c0479a0fb867619,mecka,2700.0,cleaning_engine_parts,"A mechanic continues to clean a used, three-cy...",service_bay,"[""engine_gasket"", ""workbench"", ""cloth""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b2152...,,s3://rldb/processed_v3/mecka/freeform/696b2152...,None,None
2,696bcb732a9a68766920de81,696452cf83a9fdf2d86552c5,mecka,2252.0,folding_paper_bags,"A person begins folding a new paper bag, caref...",packaging_area,"[""paper_sheet"", ""glue"", ""plastic_container"", ""...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,None,None
3,69b4944484179943aec080c6,6948bbeb5c0479a0fb82ec42,mecka,2278.0,planting_cuttings,Planting plant cuttings into a tray filled wit...,nursery,"[""soil"", ""plant_cuttings"", ""tray"", ""pots""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/69b49444...,,s3://rldb/processed_v3/mecka/freeform/69b49444...,CC BY-SA 4.0,"[{'label': 'adjust soil in container', 'end_se..."
4,693cd014bec8abdc94f9a365,693369d4c195d3a38a24af5c,mecka,2650.0,labeling_eggs,The person uses a pair of scissors to cut labe...,packing_shed,"[""labels"", ""egg_cartons"", ""eggs""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/693cd014...,,s3://rldb/processed_v3/mecka/freeform/693cd014...,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72259,696db125ddefc568d7372680,695b04fc83a9fdf2d8485831,mecka,2698.0,packaging_items,"A person is sitting and packaging small, black...",material_storage,"[""air_stones"", ""plastic_bags"", ""cardboard_box""...",s3://rldb/mecka/freeform/696db125ddefc568d7372680,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696db125...,,s3://rldb/processed_v3/mecka/freeform/696db125...,CC BY-SA 4.0,"[{'label': 'pick up plastic bag, pick up grey ..."
72260,696b9a50a04610abd4bb2ed0,694901865c0479a0fb833c40,mecka,2848.0,decorating_party_horns,A person attaches a pre-made blue fringed pape...,craft_section,"[""party_horn"", ""blue_fringed_paper"", ""white_fr...",s3://rldb/mecka/freeform/696b9a50a04610abd4bb2ed0,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,CC BY-SA 4.0,"[{'label': 'wrap fringe, adjust cone', 'end_se..."
72261,696bac1d7e6f94bf3414388d,6951c933c0d9448524bb1d46,mecka,3598.0,making_kites,A person continues to assemble a kite frame. T...,craft_section,"[""kite_frame"", ""bamboo_sticks"", ""string""]",s3://rldb/mecka/freeform/696bac1d7e6f94bf3414388d,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,CC BY-SA 4.0,[{'label': 'tie two wooden sticks to form a cr...
72262,696babf5b17075c2c32fa74b,694c877362d08e8cd95f46fd,mecka,3598.0,cleaning_shoes,A person is using a brush and soapy water to s...,repair_bench,"[""shoe"", ""soapy_water""]",s3://rldb/mecka/freeform/696babf5b17075c2c32fa74b,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696babf5...,,s3://rldb/processed_v3/mecka/freeform/696babf5...,CC BY-SA 4.0,"[{'label': 'hold shoe, scrub shoe with brush',..."
72263,696bbd5575020a567fd376e9,6959d51cb8d0e4dc08fb48e1,mecka,3202.0,wick_preparation,"The person continues preparing candle wicks, c...",production_area,"[""tealight_cup"", ""wooden_sticks"", ""wick"", ""met...",s3://rldb/mecka/freeform/696bbd5575020a567fd376e9,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,CC BY-SA 4.0,"[{'label': 'pick up sticks, align sticks', 'en..."

In [ ]:
# Flagship Fold Clothes Data
df[(df["task"] == "fold_clothes") & df["lab"].isin(["rl2", "eth", "song", "wang"])]