In [1]:
from sqlalchemy import (
    Boolean,
    Column,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    text,
    update,
)

from egomimic.utils.aws.aws_sql import (
    TableRow,
    create_default_engine,
    episode_table_to_df,
)

In [2]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [3]:
df = episode_table_to_df(engine)
df

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
0,696bc6351cafc9f413b5b7e8,695d098f83a9fdf2d84d9a47,mecka,1960.0,packaging_cloths,"In the final part of the video, the person con...",stockroom,"[""plaid_cloths"", ""plastic_bags"", ""cardboard_bo...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bc635...,,s3://rldb/processed_v3/mecka/freeform/696bc635...,None,None
1,696b2152d1aa1f60b4db5ef1,694a6ead5c0479a0fb867619,mecka,2700.0,cleaning_engine_parts,"A mechanic continues to clean a used, three-cy...",service_bay,"[""engine_gasket"", ""workbench"", ""cloth""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b2152...,,s3://rldb/processed_v3/mecka/freeform/696b2152...,None,None
2,696bcb732a9a68766920de81,696452cf83a9fdf2d86552c5,mecka,2252.0,folding_paper_bags,"A person begins folding a new paper bag, caref...",packaging_area,"[""paper_sheet"", ""glue"", ""plastic_container"", ""...",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,None,None
3,69b4944484179943aec080c6,6948bbeb5c0479a0fb82ec42,mecka,2278.0,planting_cuttings,Planting plant cuttings into a tray filled wit...,nursery,"[""soil"", ""plant_cuttings"", ""tray"", ""pots""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/69b49444...,,s3://rldb/processed_v3/mecka/freeform/69b49444...,CC BY-SA 4.0,"[{'label': 'adjust soil in container', 'end_se..."
4,693cd014bec8abdc94f9a365,693369d4c195d3a38a24af5c,mecka,2650.0,labeling_eggs,The person uses a pair of scissors to cut labe...,packing_shed,"[""labels"", ""egg_cartons"", ""eggs""]",None,None,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/693cd014...,,s3://rldb/processed_v3/mecka/freeform/693cd014...,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58313,692ee049ef7557106e6c4b99,678d5c6368e425c008acaea5,mecka,66.0,object_in_container,,,,s3://rldb/mecka/flagship/692ee049ef7557106e6c4...,rldb:/mecka/flagship/692ee049ef7557106e6c4b99_...,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/flagship/692ee049...,,s3://rldb/processed_v3/mecka/flagship/692ee049...,CC BY-SA 4.0,None
58314,692ee046ef7557106e6c4b80,678d5c6368e425c008acaea5,mecka,110.0,object_in_container,,,,s3://rldb/mecka/flagship/692ee046ef7557106e6c4...,rldb:/mecka/flagship/692ee046ef7557106e6c4b80_...,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/flagship/692ee046...,,s3://rldb/processed_v3/mecka/flagship/692ee046...,CC BY-SA 4.0,None
58315,692eab58b8797912ff78a859,6768a79a7fdec9138007a095,mecka,113.0,object_in_container,,,,s3://rldb/mecka/flagship/692eab58b8797912ff78a...,rldb:/mecka/flagship/692eab58b8797912ff78a859_...,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/flagship/692eab58...,,s3://rldb/processed_v3/mecka/flagship/692eab58...,CC BY-SA 4.0,None
58316,696bbd5575020a567fd376e9,6959d51cb8d0e4dc08fb48e1,mecka,3202.0,wick_preparation,"The person continues preparing candle wicks, c...",production_area,"[""tealight_cup"", ""wooden_sticks"", ""wick"", ""met...",s3://rldb/mecka/freeform/696bbd5575020a567fd376e9,rldb:/mecka/freeform/696bbd5575020a567fd376e9_...,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,CC BY-SA 4.0,"[{'label': 'pick up sticks, align sticks', 'en..."
58317,692eaaa796d2056439f018ab,6768a79a7fdec9138007a095,mecka,114.0,object_in_container,,,,s3://rldb/mecka/flagship/692eaaa796d2056439f01...,rldb:/mecka/flagship/692eaaa796d2056439f018ab_...,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/flagship/692eaaa7...,,s3://rldb/processed_v3/mecka/flagship/692eaaa7...,CC BY-SA 4.0,None

In [4]:
# Filter to certain lab
len(df[df["task"] == "cup_on_saucer_success_1"])

323

In [5]:
df_filtered = df[df["task"] == "cup_on_saucer_success_1"]
print("Counts for each object value:")
print(df_filtered["objects"].value_counts())

Counts for each object value:
objects
{"white cup","white saucer"}                   42
{"pink cup","white saucer"}                    41
{"white cup","green square saucer"}            40
{"white cup","yellow saucer"}                  40
{"white ceramic cup","yellow saucer"}          40
{"white ceramic cup","white saucer"}           40
{"white ceramic cup","green square saucer"}    40
{"pink cup","green square saucer"}             40
Name: count, dtype: int64

In [6]:
len(df[df["task"] == "cup_on_saucer_failure_1"])

52

In [7]:
df_filtered = df[df["task"] == "cup_on_saucer_failure_1"]
print("Counts for each object value:")
print(df_filtered["objects"].value_counts())

Counts for each object value:
objects
{"white ceramic cup","yellow saucer"}          11
{"white cup","yellow saucer"}                   9
{"white ceramic cup","white saucer"}            9
{"white cup","green square saucer"}             7
{"pink cup","green square saucer"}              6
{"pink cup","white saucer"}                     5
{"white cup","white saucer"}                    3
{"white ceramic cup","green square saucer"}     2
Name: count, dtype: int64

In [8]:
df[df["task"] == "cup_on_saucer_success_1"]

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
9,2026-03-27-22-31-39-884000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""green square saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
34,2026-03-27-22-33-09-391000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""green square saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
38,2026-03-27-22-37-03-390000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""green square saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
39,2026-03-27-22-37-41-308000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""green square saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
40,2026-03-27-22-38-17-083000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""green square saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,2026-03-28-22-13-32-556000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
2849,2026-03-28-22-14-06-503000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
2851,2026-03-28-22-14-36-891000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
2855,2026-03-28-22-15-11-105000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None
2862,2026-03-28-22-15-44-138000,Baoyu,rl2,-1.0,cup_on_saucer_success_1,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer""}",,,...,eva_bimanual,False,-1.0,True,,,,,None,None

In [9]:
# Flagship Fold Clothes Data
# df[(df["task"] == "fold_clothes") & df["lab"].isin(["rl2", "eth", "song", "wang"])]