In [1]:
from sqlalchemy import (
    MetaData,
    Table,
    Column,
    Integer,
    String,
    Boolean,
    Float,
    text,
    update,
    select
)
from egomimic.utils.aws.aws_sql import (
    TableRow,
    add_episode,
    update_episode,
    create_default_engine,
    episode_hash_to_table_row,
    delete_episodes,
    episode_table_to_df,
    delete_all_episodes,
)

In [2]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [3]:
df = episode_table_to_df(engine)
df

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,is_deleted,embodiment,robot_name,is_eval,eval_score,eval_success,processing_error
0,2025-10-29-22-05-17-825000,Lawrence,rl2,-1,fold clothes,folding clothes,8,"{""short sleeve shirts"",""long sleeve shirts"",sh...",,,False,aria,aria_bimanual,False,-1.0,True,
1,2025-10-29-21-54-36-193000,Aniketh,rl2,-1,fold clothes,folding clothes,1,"{""short sleeve shirts"",""long sleeve shirts"",sh...",,,False,aria,aria_bimanual,False,-1.0,True,
2,2025-11-13-01-14-53-715000,elmo,rl2,-1,move_caprisun,move caprison from one fixed region to another...,scene2,{caprisun},,,True,eva,eva,False,-1.0,True,
3,2025-11-11-22-54-29-457000,rl2,rl2,1400,fold clothes,folding clothes,7,"{""short sleeve shirts"",""long sleeve shirts"",sh...",s3://rldb/processed_v2/aria/2025-11-11-22-54-2...,s3://rldb/processed_v2/aria/1762901669457_vide...,False,aria,aria_bimanual,False,-1.0,True,
4,2025-12-27-21-34-49-000000,Yangcen,rl2,3800,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-27-21-34-4...,s3://rldb/processed_v2/aria/1766871289000_vide...,False,aria,aria_bimanual,False,-1.0,True,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43180,692bdbd5c1f3792af4224bf9,691ac281ae3392603547f58e,mecka,2998,sweeping_floor,Actively sweeping a large pile of accumulated ...,bedroom,"[""trash"", ""wrappers"", ""paper""]",s3://rldb/mecka/freeform/692bdbd5c1f3792af4224...,rldb:/mecka/freeform/692bdbd5c1f3792af4224bf9_...,False,mecka,mecka_bimanual,False,-1.0,True,
43181,692b854d09dfb12d007321ff,68220a1f6d15614293332734,mecka,3070,sweeping,A person is sweeping a patterned Persian rug w...,living_room,"[""rug"", ""cushions""]",s3://rldb/mecka/freeform/692b854d09dfb12d00732...,rldb:/mecka/freeform/692b854d09dfb12d007321ff_...,False,mecka,mecka_bimanual,False,-1.0,True,
43182,692b706765dde00e79456663,691ac281ae3392603547f58e,mecka,3148,sweeping_floors,Sweeping trash and debris from a tiled floor i...,bedroom,"[""trash"", ""paper_wrappers""]",s3://rldb/mecka/freeform/692b706765dde00e79456...,rldb:/mecka/freeform/692b706765dde00e79456663_...,False,mecka,mecka_bimanual,False,-1.0,True,
43183,692bc3ed6e5b930798610c12,691ac281ae3392603547f58e,mecka,2992,sweeping_floor,A person is sweeping trash from a tiled floor ...,bedroom,"[""trash"", ""wrappers"", ""paper""]",s3://rldb/mecka/freeform/692bc3ed6e5b930798610...,rldb:/mecka/freeform/692bc3ed6e5b930798610c12_...,False,mecka,mecka_bimanual,False,-1.0,True,
43184,691a6311a6a3fc2efb40befe,68f8292d151ed264839acd2e,mecka,2314,vacuuming,A person wearing a Batman sweatshirt uses a va...,bedroom,"[""mattress"", ""vacuum_cleaner"", ""clothes_rack""]",s3://rldb/mecka/freeform/691a6311a6a3fc2efb40b...,rldb:/mecka/freeform/691a6311a6a3fc2efb40befe_...,False,mecka,mecka_bimanual,False,-1.0,True,

## Example Useful Functions

In [7]:
# Add Episode Test
episode = TableRow(
    episode_hash=1761408819,
    operator="test-lawrence",
    lab="lab-x",
    num_frames=-1,
    task="bimanual_test",
    task_description="Dummy row for table inspection",
    scene="kitchen",
    objects="cup,plate,spoon",
    processed_path="",
    mp4_path="",
    embodiment="aria",
    robot_name="",
    is_eval=False,
    eval_score=0.0,
    eval_success=False,
)
# Adding an episode
# add_episode(engine, episode)

# Update Episode Test
# episode.operator = "simar"
# update_episode(engine, episode)

# Get Table Row from Episode Hash
# episode_hash_to_table_row(engine, 123456)

# Delete episodes by hash
# delete_episodes(engine, [123456, 123457])

In [ ]:
# # Mark episodes as deleted in SQL by episode_hash (dry run first)
# from pathlib import Path
# from tqdm import tqdm

# # Input list from checker
# corrupted_path = Path(
#     "/nethome/yzhu827/flash/shared/EgoVerse/egomimic/scripts/frozen_front_img_1_stride60.txt"
# )

# corrupted_ids = [
#     line.strip() for line in corrupted_path.read_text().splitlines() if line.strip()
# ]


# def delete_episodes_by_hash(episode_hashes: list[str], *, dry_run: bool = True) -> None:
#     episodes_tbl = Table("episodes", MetaData(), autoload_with=engine, schema="app")
#     stmt = (
#         update(episodes_tbl)
#         .where(episodes_tbl.c.episode_hash.in_(episode_hashes))
#         .values(is_deleted=True)
#     )
#     if dry_run:
#         print(f"[DRY RUN] would update {len(episode_hashes)} rows")
#         return
#     with engine.begin() as conn:
#         conn.execute(stmt)


# dry_run = False

# # Process in batches for safety
# batch_size = 500
# for i in range(0, len(corrupted_ids), batch_size):
#     batch = corrupted_ids[i : i + batch_size]
#     print(f"Batch {i // batch_size + 1}: {len(batch)} episodes")
#     delete_episodes_by_hash(batch, dry_run=dry_run)

# print(f"Done. dry_run={dry_run}")

Batch 1: 54 episodes
Done. dry_run=False

In [11]:
# Load episode_hash list from txt for SQL updates
from pathlib import Path

corrupted_path = Path(
    "/nethome/yzhu827/flash/shared/EgoVerse/egomimic/scripts/frozen_front_img_1_stride60.txt"
)

corrupted_ids = [
    line.strip() for line in corrupted_path.read_text().splitlines() if line.strip()
]

print(f"Loaded {len(corrupted_ids)} episode hashes")
print(corrupted_ids[:5])

Loaded 54 episode hashes
['2026-01-01-22-25-32-357000', '2026-01-01-22-26-07-236000', '2026-01-01-22-26-41-490000', '2026-01-01-22-27-20-945000', '2026-01-01-22-28-02-757000']

In [12]:
# Load full SQL rows for corrupted episodes
import pandas as pd

# Pull full table and filter to corrupted episode_hash list
sql_df = episode_table_to_df(engine)
corrupted_df = sql_df[sql_df["episode_hash"].isin(corrupted_ids)].copy()

print(f"Total rows: {len(sql_df)}, corrupted rows: {len(corrupted_df)}")
corrupted_df

Total rows: 43185, corrupted rows: 54

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,is_deleted,embodiment,robot_name,is_eval,eval_score,eval_success,processing_error
630,2026-01-01-22-25-32-357000,Ryan,rl2,1560,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-25-32...,rldb:/processed_v2/eva/1767306332357_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
631,2026-01-04-03-25-27-608000,Ryan,rl2,670,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-25-27...,rldb:/processed_v2/eva/1767497127608_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
632,2026-01-04-03-36-26-041000,Ryan,rl2,764,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-36-26...,rldb:/processed_v2/eva/1767497786041_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
633,2026-01-04-03-34-27-985000,Ryan,rl2,779,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-34-27...,rldb:/processed_v2/eva/1767497667985_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
634,2026-01-04-03-37-09-871000,Ryan,rl2,804,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-37-09...,rldb:/processed_v2/eva/1767497829871_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
636,2026-01-04-03-37-55-167000,Ryan,rl2,834,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-37-55...,rldb:/processed_v2/eva/1767497875167_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
637,2026-01-04-03-46-18-153000,Ryan,rl2,676,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-46-18...,rldb:/processed_v2/eva/1767498378153_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
638,2026-01-04-03-47-50-545000,Ryan,rl2,736,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-47-50...,rldb:/processed_v2/eva/1767498470545_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
639,2026-01-04-03-52-13-233000,Ryan,rl2,762,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-52-13...,rldb:/processed_v2/eva/1767498733233_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
640,2026-01-04-03-56-00-286000,Ryan,rl2,724,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-56-00...,rldb:/processed_v2/eva/1767498960286_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
641,2026-01-04-03-40-09-455000,Ryan,rl2,821,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-40-09...,rldb:/processed_v2/eva/1767498009455_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
642,2026-01-04-03-59-13-146000,Ryan,rl2,794,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-59-13...,rldb:/processed_v2/eva/1767499153146_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
644,2026-01-04-03-50-05-341000,Ryan,rl2,898,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-50-05...,rldb:/processed_v2/eva/1767498605341_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
645,2026-01-04-04-07-15-324000,Ryan,rl2,730,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-07-15...,rldb:/processed_v2/eva/1767499635324_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
647,2026-01-04-03-58-16-243000,Ryan,rl2,905,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-58-16...,rldb:/processed_v2/eva/1767499096243_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
648,2026-01-04-04-08-43-467000,Ryan,rl2,903,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-08-43...,rldb:/processed_v2/eva/1767499723467_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
668,2026-01-04-03-59-58-739000,Ryan,rl2,950,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-59-58...,rldb:/processed_v2/eva/1767499198739_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
669,2026-01-04-04-11-56-550000,Ryan,rl2,785,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-11-56...,rldb:/processed_v2/eva/1767499916550_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
670,2026-01-04-04-12-29-592000,Ryan,rl2,818,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-12-29...,rldb:/processed_v2/eva/1767499949592_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
672,2026-01-04-03-26-32-278000,Ryan,rl2,769,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-26-32...,rldb:/processed_v2/eva/1767497192278_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
673,2026-01-04-03-27-42-439000,Ryan,rl2,805,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-27-42...,rldb:/processed_v2/eva/1767497262439_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
674,2026-01-04-03-48-34-449000,Ryan,rl2,750,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-48-34...,rldb:/processed_v2/eva/1767498514449_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
675,2026-01-04-03-45-46-634000,Ryan,rl2,722,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-45-46...,rldb:/processed_v2/eva/1767498346634_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
676,2026-01-04-03-51-27-623000,Ryan,rl2,776,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-51-27...,rldb:/processed_v2/eva/1767498687623_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
677,2026-01-04-04-05-56-240000,Ryan,rl2,747,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-05-56...,rldb:/processed_v2/eva/1767499556240_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
678,2026-01-04-03-56-36-604000,Ryan,rl2,776,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-56-36...,rldb:/processed_v2/eva/1767498996604_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
679,2026-01-04-04-01-43-029000,Ryan,rl2,796,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-01-43...,rldb:/processed_v2/eva/1767499303029_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
681,2026-01-04-04-09-23-457000,Ryan,rl2,669,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-09-23...,rldb:/processed_v2/eva/1767499763457_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
682,2026-01-04-03-50-51-654000,Ryan,rl2,935,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-50-51...,rldb:/processed_v2/eva/1767498651654_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
683,2026-01-04-03-55-21-017000,Ryan,rl2,974,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-55-21...,rldb:/processed_v2/eva/1767498921017_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
685,2026-01-04-04-11-00-627000,Ryan,rl2,777,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-11-00...,rldb:/processed_v2/eva/1767499860627_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
687,2026-01-04-04-16-45-654000,Ryan,rl2,892,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-16-45...,rldb:/processed_v2/eva/1767500205654_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
705,2026-01-04-04-18-39-397000,Ryan,rl2,859,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-18-39...,rldb:/processed_v2/eva/1767500319397_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
707,2026-01-04-04-18-01-802000,Ryan,rl2,955,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-18-01...,rldb:/processed_v2/eva/1767500281802_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
708,2026-01-04-03-39-30-030000,Ryan,rl2,1222,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-39-30...,rldb:/processed_v2/eva/1767497970030_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
709,2026-01-04-04-00-56-622000,Ryan,rl2,910,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-00-56...,rldb:/processed_v2/eva/1767499256622_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
710,2026-01-04-04-10-26-843000,Ryan,rl2,942,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-10-26...,rldb:/processed_v2/eva/1767499826843_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
711,2026-01-04-04-06-43-977000,Ryan,rl2,1130,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-06-43...,rldb:/processed_v2/eva/1767499603977_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
712,2026-01-04-04-16-06-801000,Ryan,rl2,865,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-16-06...,rldb:/processed_v2/eva/1767500166801_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
713,2026-01-04-03-24-57-913000,Ryan,rl2,876,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-24-57...,rldb:/processed_v2/eva/1767497097913_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
714,2026-01-04-03-47-02-737000,Ryan,rl2,712,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-47-02...,rldb:/processed_v2/eva/1767498422737_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
715,2026-01-04-03-54-39-226000,Ryan,rl2,771,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-54-39...,rldb:/processed_v2/eva/1767498879226_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
716,2026-01-04-03-52-52-635000,Ryan,rl2,846,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-52-52...,rldb:/processed_v2/eva/1767498772635_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
717,2026-01-04-04-02-31-891000,Ryan,rl2,988,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-02-31...,rldb:/processed_v2/eva/1767499351891_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
718,2026-01-04-04-07-56-064000,Ryan,rl2,855,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-07-56...,rldb:/processed_v2/eva/1767499676064_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
719,2026-01-04-03-38-43-821000,Ryan,rl2,938,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-38-43...,rldb:/processed_v2/eva/1767497923821_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
720,2026-01-04-04-19-15-054000,Ryan,rl2,722,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-04-19-15...,rldb:/processed_v2/eva/1767500355054_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
771,2026-01-01-22-26-41-490000,Ryan,rl2,945,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-26-41...,rldb:/processed_v2/eva/1767306401490_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
856,2026-01-01-22-26-07-236000,Ryan,rl2,918,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-26-07...,rldb:/processed_v2/eva/1767306367236_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
857,2026-01-01-22-27-20-945000,Ryan,rl2,1151,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-27-20...,rldb:/processed_v2/eva/1767306440945_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
858,2026-01-01-22-28-02-757000,Ryan,rl2,1223,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-28-02...,rldb:/processed_v2/eva/1767306482757_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
859,2026-01-01-22-28-51-953000,Ryan,rl2,1517,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-28-51...,rldb:/processed_v2/eva/1767306531953_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
860,2026-01-01-22-29-23-631000,Ryan,rl2,1004,fold clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-01-22-29-23...,rldb:/processed_v2/eva/1767306563631_video.mp4,True,eva,eva_bimanual,False,-1.0,True,
1147,2026-01-04-03-35-11-837000,Ryan,rl2,899,fold clothes,fold the t-shirt,1,"{""lightblue medium t-shirt""}",s3://rldb/processed_v2/eva/2026-01-04-03-35-11...,rldb:/processed_v2/eva/1767497711837_video.mp4,True,eva,eva_bimanual,False,-1.0,True,

In [ ]:
def drop_table(table_name):
    with engine.connect() as connection:
        connection.execute(text(f"DROP TABLE IF EXISTS app.{table_name} CASCADE;"))
        connection.commit()
    print(f"Dropped table '{table_name}' from schema 'app' if it existed.")

In [ ]:
def create_table():
    metadata = MetaData(schema="app")

    Table(
        "episodes",
        metadata,
        Column("episode_hash", String, primary_key=True),
        Column("operator", String),
        Column("lab", String),
        Column("num_frames", Integer),
        Column("task", String),
        Column("task_description", String),
        Column("scene", String),
        Column(
            "objects", String
        ),  # Store as JSON or comma-separated list of object names
        Column("processed_path", String),
        Column("mp4_path", String),
        Column("is_deleted", Boolean),
        Column("embodiment", String),
        Column("robot_name", String),
        Column("is_eval", Boolean),
        Column("eval_score", Float),
        Column("eval_success", Boolean),
    )

    metadata.create_all(engine)
    print("Created table 'episodes' in schema 'app'.")

In [ ]:
def delete_episodes_by_task(task_name: str):
    episodes_tbl = Table("episodes", MetaData(), autoload_with=engine, schema="app")
    stmt = (
        update(episodes_tbl)
        .where(episodes_tbl.c.task == task_name)
        .values(is_deleted=True)
    )
    with engine.begin() as conn:
        conn.execute(stmt)